### ISSUE TITLE
Vertical Site Navigation

### ISSUE THREAD

**Issue by nicdford** [washingtonstateuniversity/wsu-web-design-system#16]
## Mockup
[vertnav-v4.pdf](https://github.com/washingtonstateuniversity/wsu-web-design-system/files/3843793/vertnav-v4.pdf)

## Task List
- [x] First menu item should animate in followed by the rest
- [x] Isolate expand/collapse from the keyboard accessibility functionality
- [x] Add keyboard navigation support to vertical navigation
- [x] Ensure all menu items expand/collapse correctly
- [x] Fix plus/minus arrow on expand/collapse
- [x] Fix issue with css not display aria-expanded menu items properly on toggle at all nav levels
- [x] Test to make sure keyboard navigation support is working correctly with expand/collapse
- [x] Fix close button alignment on slideout panel
- [x] Create method so slideout panel pushes content over without rewrapping the content when the screen size is larger than 1920px
- [x] Ensure all menu items expand by default if js is disabled
- [x] Ensure `--active` class name tag is working on menu item links at all nav levels
- [x] Create method for closing menu when a user clicks on the "disabled" screen area (the color overlay)
- [ ] Create "tree mode" that makes navigation only act like a traditional tree structure (clicking on parent takes to new page and exposes sub pages)
- [ ] Go through various screen sizes and ensure it's functioning as intended (see agreed upon behaviors)

### Misc Questions
- We should probably be using button elements instead of anchor links... Does anyone have any strong opinions on this? or at the very least, but a role of button on anchor links?
- How do we handle "--is-active" modifier, does it automatically expose that menu item to user in js? Or is there a different way to handle this that i'm not thinking of?

**Comment by nicdford** [comment]
Agreed upon behaviors: 
- On Desktop (something greater than ~1500px) the vertical nav will reflow/push content to make room for navigation
- On “Tablet”, navigation pushes content over, applies color overlay, and overlay acts as a close method
- On "Ultra wide" (something greater than 1920px), don’t center content, attach to left side with a fixed distance
- On "mobile", same as tablet (Push content over, etc., etc.)
- Coug head will be an inline svg for all components
