### ISSUE TITLE
Content Icons

### ISSUE THREAD

**Issue by nicdford** [washingtonstateuniversity/wsu-web-design-system#24]
## Creating a WSU icon font will aim to solve the following problems:

- Allow us to modify color dynamically with css without having to inline the SVG
- Allow us to modify/update icons in a set and have them update based on a versioning structure (if we need to modify an icon it can update automatically throughout the system instead of having to be adopted manually)
- Have different font sets (light, regular, bold) using a class name prefix ([Font Awesome uses fas for solid, far for regular, fal for light, etc.](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use))
- Allow users to easily implement icons in their markup using html class names `<span class="wsu-icon-reg wsu-icon-phone"></span>` (or something like this)
- Removes inline markup loader dependency in webpack config 

## Tasks

- [x] Remove all previous SVG only implementation (webpack config, icons in folders, etc.)
- [x] Finalize icon set with @jasonbittle 
- [x] Create icon font (http://fontello.com/ http://fontastic.me/ https://icomoon.io/app/#/select or something similiar)
- [x] Implement into design system (HTML class helpers)
- [x] Need to reexport icon set using artboards @jasonbittle 
- [x] Regenerate icon set @nicdford

**Comment by nicdford** [comment]
Closed by #43

**Comment by nicdford** [comment]
Reopen issue to serve as parent issue for further content hero development.
