### ISSUE TITLE
Video Component

### ISSUE THREAD

**Issue by nicdford** [washingtonstateuniversity/wsu-web-design-system#96]
**Is your feature request related to a problem? Please describe.**
The video component would provide a consistent UI for all videos regardless of their source (YouTube, Vimeo, Media Library, Etc.). 

**Describe the solution you'd like**
[VideoJS](https://videojs.com/) or [Plyr](https://plyr.io/) seem like good viable options for handling some of the heavy lifting. We don't want to re-invent the wheel, but do need an option that allows us to control the UI so we can better brand videos on the Website.

Specific Video Player Controls would include (needs input):

- [ ] Play / Pause Button
- [ ] Progress / Loading / Seeking Bar
- [ ] Volume Controls
- [ ] Mute / unMute Button
- [ ] Close Captioning on/off button
- [ ] Video Settings Controls (speed, quality, CC language)
- [ ] Picture-in-Picture (PIP) Button (Would also automatically happen when video is out of current viewport and playing)
- [ ] Fullscreen button
